- name: variables from files
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
    private: false # it is not confidential information
  - name: DURATION
    prompt: please enter duration name
    private: false 
  - name: TRAINER
    prompt: please enter Trainer name
    private: false 
  tasks: 
  - name: print course information
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"