- name: check value is grater than 12 or not
  hosts: local
  connection: local
  vars:
    my_number: 16
  tasks: 
  - name: print if number is greter than 10
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is greater than 10"
    when: my_number > 10 

  - name: print if number is less than  or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is less than  or equal to 10"
    when: my_number > 10 