- name: Install Nginx
  hosts: web
  become: yes
  tasks:
  - name: install ndinx if RHEL
    ansible.builtin.debug:
      name: nginx
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install ndinx if Ubuntu
    ansible.builtin.apt:
      name: nginx
      state: installed
    when: ansible_os_family == "Debian"