# - name: loop
#   hosts: local
#   connection: local
#   tasks:
#   - name: print loops
#     ansible.builtin.debug:
#       msg: "Hello {{ item }}"
#     loop:
#     - Pavan
#     - chouda
#     - Ramesh

# Install packages
- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: Iistall packages
    ansible.built.in.packages:
      name: "{{ items }}"
      state: installed
    loop:
    - gcc
    - git
    - mysql
    - zip

