# - name: loop
#   hosts: local
#   connection: local
#   tasks:
#   - name: print loops
#     ansible.builtin.debug:
#       msg: "Hello {{ item }}"
#     loop:
#     - Pavan
#     - chouda
#     - Ramesh

  # Install packages
# - name: install packages
#   hosts: web
#   become: yes
#   tasks:
#   - name: install packages
#     ansible.builtin.package:
#       name: "{{ item }}"
#       state: installed
#     loop:
#     - gcc
#     - git
#     - mysql
#     - zip

  # Install/uninstall packages
- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'gcc', state: 'absent' }
    - { name: 'git', state: 'present' }
    - { name: 'mysql', state: 'absent' }
    - { name: 'zip', state: 'pesent' }
