- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('pavan') }}"

  - name: convert string into list
    vars:
      fruits: "apple, banana, mango, orange" #string
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"

  - name: Convert maps into list
    vars:
      course:
        name: ansible
        duration: 10hrs
        traniee: Sivakumar
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: Convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'traniee', 'value': 'Sivakumar'}
      ansible.builtin.debug:
        msg: "Course info {{ Course | items2dict }}"
