- name: create ec2 and r53 records
  connection: local
  hosts: local
  #become: yes
  vars:
    subnet_id: subnet-08f7091e904498495
    sg_id: sg-0858b522e979486c3
    ami_id: ami-09c813fb71547fc4f
    #region: us-east-1
    instance_type: t3.micro
    zone: pavanreddy.store
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install AWS python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
      #region: "{{ region }}"
    loop: "{{ instances }}"
    register: ec2_info

  - name: print ec2_info
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"

  - name: print private ip address
    ansible.builtin.debug:
      msg: "{{item.instances[0].private_ip_address }}"
    loop:  "{{ ec2_info.results }}"

  - name: create private in r53 records
    amazon.aws.route53:
      state: present
      zone: '{{ zone }}'
      record: "{{ item.item }}.{{ zone}}"
      type: A
      value: "{{item.instances[0].private_ip_address }}"
      ttl: 1
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"

  - name: create public ip for frontend
    amazon.aws.route53:
      state: present
      zone: '{{ zone }}'
      record: "{{ zone }}"
      type: A
      value: "{{item.instances[0].public_ip_address }}"
      ttl: 1
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"
    when: item.item == "frontend"
  
