- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-08f7091e904498495
    sg_id: sg-0858b522e979486c3
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install AWS python libraries
    ansible.builtin.pip:
      name: " {{ item }}"
      executable: pip3.9
    loop:
    - boto3
    
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{instances }}"